# Generated by Django 4.2.6 on 2023-11-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='name',
        ),
    ]
