# Generated by Django 4.2.6 on 2023-11-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_course_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_profile',
        ),
    ]
