# Generated by Django 4.2.6 on 2023-11-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='app.course'),
        ),
    ]
